// src/constants/species.ts
import { BirdSpecies } from '@/types/birds';

export const BIRD_SPECIES: BirdSpecies[] = [
        { name: "Авдотка (Burhinus oedicnemus)", family: "Авдотковые", status: "исчезающий", statusClass: "status-endangered", statusText: "Исчезающий вид" },
        { name: "Балобан (Falco cherrug)", family: "Соколиные", status: "исчезающий", statusClass: "status-endangered", statusText: "Исчезающий вид" },
        { name: "Белогорлый рогатый жаворонок (Eremophila alpestris brandti)", family: "Жаворонковые", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Беркут (Aquila chrysaetos Linnaeus)", family: "Ястребиные", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Большая белая цапля (Egretta alba Linnaeus)", family: "Цаплевые", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Большой кроншнеп (Numenius arquata Linnaeus)", family: "Бекасовые", status: "уязвимый", statusClass: "status-vulnerable", statusText: "Уязвимый вид" },
        { name: "Большой подорлик (Aquila clanga Pallas)", family: "Ястребиные", status: "исчезающий", statusClass: "status-endangered", statusText: "Исчезающий вид" },
        { name: "Горная чечётка (Carduelis flavirostris)", family: "Вьюрковые", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Дрофа (Otis tarda Linnaeus)", family: "Дрофиные", status: "исчезающий", statusClass: "status-endangered", statusText: "Исчезающий вид" },
        { name: "Европейская белая лазоревка (Cyanistes cyanus Pallas)", family: "Синицевые", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Европейский средний дятел (Leiopicus medius)", family: "Дятловые", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Европейский тювик (Accipiter brevipes)", family: "Ястребиные", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Змееяд (Circaetus gallicus Gmelin)", family: "Ястребиные", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Каменный воробей (Petronia petronia)", family: "Воробьиные", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Колпица (Platalea leucorodia Linnaeus)", family: "Ибисовые", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Красавка (Anthropoides virgo)", family: "Журавлиные", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Краснозобая казарка (Branta ruficollis)", family: "Утиные", status: "исчезающий", statusClass: "status-endangered", statusText: "Исчезающий вид" },
        { name: "Кречётка (Vanellus gregarius)", family: "Ржанковые", status: "исчезающий", statusClass: "status-endangered", statusText: "Исчезающий вид" },
        { name: "Кудрявый пеликан (Pelecanus crispus Bruch)", family: "Пеликановые", status: "исчезающий", statusClass: "status-endangered", statusText: "Исчезающий вид" },
        { name: "Курганник (Buteo rufinus Cretzschmar)", family: "Ястребиные", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Малая крачка (Sterna albifrons Pallas)", family: "Чайковые", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Малый лебедь (Cygnus columbianus bewickii)", family: "Утиные", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Материковый кулик-сорока (Haematopus ostralegus)", family: "Кулики-сороки", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Могильник (Aquila heliaca Savigny)", family: "Ястребиные", status: "исчезающий", statusClass: "status-endangered", statusText: "Исчезающий вид" },
        { name: "Морской зуёк (Charadrius alexandrinus)", family: "Ржанковые", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Обыкновенный серый сорокопут (Lanius excubitor Linnaeus)", family: "Сорокопутовые", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Обыкновенный фламинго (Phoenicopterus roseus Pallas)", family: "Фламинговые", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Орлан-белохвост (Haliaeetus albicilla)", family: "Ястребиные", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Орлан-долгохвост (Haliaeetus leucoryphus)", family: "Ястребиные", status: "исчезающий", statusClass: "status-endangered", statusText: "Исчезающий вид" },
        { name: "Пискулька (Anser erythropus)", family: "Утиные", status: "исчезающий", statusClass: "status-endangered", statusText: "Исчезающий вид" },
        { name: "Розовый скворец (Sturnus roseus)", family: "Скворцовые", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Сапсан (Falco peregrinus)", family: "Соколиные", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Серая неясыть (Strix aluco Linnaeus)", family: "Совиные", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Скопа (Pandion haliaetus)", family: "Скопиные", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Сплюшка (Otus scops Linnaeus)", family: "Совиные", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Степная пустельга (Falco naumanni Fleischer)", family: "Соколиные", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Степная тиркушка (Glareola nordmanni)", family: "Тиркушковые", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Дербник (Falco columbarius)", family: "Соколиные", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Степной жаворонок (Melanocorypha calandra)", family: "Жаворонковые", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Степной лунь (Circus macrourus)", family: "Ястребиные", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Степной орёл (Aquila nipalensis Hodgson)", family: "Ястребиные", status: "исчезающий", statusClass: "status-endangered", statusText: "Исчезающий вид" },
        { name: "Стрепет (Tetrax tetrax)", family: "Дрофиные", status: "исчезающий", statusClass: "status-endangered", statusText: "Исчезающий вид" },
        { name: "Тонкоклювый кроншнеп (Numenius tenuirostris Vieillot)", family: "Бекасовые", status: "исчезающий", statusClass: "status-endangered", statusText: "Исчезающий вид" },
        { name: "Филин (Bubo bubo)", family: "Совиные", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Ходулочник (Himantopus himantopus)", family: "Шилоклювковые", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Черноголовый хохотун (Larus ichthyaetus Pallas)", family: "Чайковые", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Чернозобая гагара (Gavia arctica Linnaeus)", family: "Гагаровые", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Чёрный аист (Ciconia nigra)", family: "Аистовые", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Черный гриф (Aegypius monachus)", family: "Ястребиные", status: "исчезающий", statusClass: "status-endangered", statusText: "Исчезающий вид" },
        { name: "Шилоклювка (Recurvirostra avosetta)", family: "Шилоклювковые", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Малый баклан (Phalacrocorax pygmeus)", family: "Баклановые", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Каравайка (Plegadis falcinellus)", family: "Ибисовые", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Белоглазый нырок (Aythya nyroca)", family: "Утиные", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Белоголовый сип (Gyps fulvus Hablizl)", family: "Ястребиные", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Стервятник (Neophron percnopterus)", family: "Ястребиные", status: "исчезающий", statusClass: "status-endangered", statusText: "Исчезающий вид" },
        { name: "Кобчик (Falco vespertinus)", family: "Соколиные", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Глухарь (Tetrao urogallus)", family: "Тетеревиные", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Большая белая куропатка (Lagopus lagopus major)", family: "Тетеревиные", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Коростель (Crex crex)", family: "Пастушковые", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Дупель (Gallinago media)", family: "Бекасовые", status: "уязвимый", statusClass: "status-vulnerable", statusText: "Уязвимый вид" },
        { name: "Большой веретенник (Limosa limosa)", family: "Бекасовые", status: "уязвимый", statusClass: "status-vulnerable", statusText: "Уязвимый вид" },
        { name: "Чайконосая крачка (Gelochelidon nilotica)", family: "Чайковые", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Бурый голубь (Columba eversmanni)", family: "Голубиные", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Вяхирь", family: "Голубиные", status: "обычный", statusClass: "status-common", statusText: "Обычный вид" },
        { name: "Сизоворонка (Coracias garrulus)", family: "Сизоворонковые", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Белокрылый жаворонок (Melanocorypha leucoptera)", family: "Жаворонковые", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Черный жаворонок (Melanocorypha yeltoniensis)", family: "Жаворонковые", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Чеграва (Hydroprogne caspia)", family: "Чайковые", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" },
        { name: "Дубровник (Ocyris aureolus)", family: "Овсянковые", status: "редкий", statusClass: "status-rare", statusText: "Редкий вид" }
];