# Generated by Django 6.0.4 on 2026-04-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observationentry',
            old_name='email',
            new_name='bird_activity',
        ),
        migrations.AddField(
            model_name='observationentry',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
