# Generated by Django 6.0.4 on 2026-05-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_email_observationentry_bird_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationentry',
            name='bird_activity',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание/заметка'),
        ),
        migrations.AlterField(
            model_name='observationentry',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='observationentry',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Активность птиц'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(blank=True, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
