# Generated by Django 6.0.4 on 2026-05-20 06:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Birds', '0004_alter_birdspecies_name_alter_location_name_and_more'),
        ('user', '0003_alter_observationentry_bird_activity_and_more'),
        ('wiki', '0006_alter_wiki_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observationentry',
            name='observation_entry',
        ),
        migrations.AddField(
            model_name='observationentry',
            name='bird_species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='Birds.birdspecies', verbose_name='Вид птицы'),
        ),
        migrations.AddField(
            model_name='observationentry',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Место наблюдения'),
        ),
        # ИЗМЕНЕНО: Сначала добавляем поле без auto_now_add
        migrations.AddField(
            model_name='observationentry',
            name='observation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата наблюдения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observationentry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='user.user', verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observationentry',
            name='wiki_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='wiki.wiki', verbose_name='Связанная статья'),
        ),
        migrations.AlterField(
            model_name='observationentry',
            name='bird_activity',
            field=models.TextField(blank=True, null=True, verbose_name='Активность птиц'),
        ),
        migrations.AlterField(
            model_name='observationentry',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='observationentry',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание/заметка'),
        ),
        # ДОБАВЛЕНО: Затем меняем на auto_now_add после заполнения данных
        migrations.AlterField(
            model_name='observationentry',
            name='observation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата наблюдения'),
        ),
    ]