# Generated by Django 6.0.4 on 2026-05-21 04:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_observationentry_observation_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationentry',
            name='observation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата наблюдения'),
        ),
    ]
