# Generated by Django 6.0.4 on 2026-05-21 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Birds', '0004_alter_birdspecies_name_alter_location_name_and_more'),
        ('user', '0005_alter_observationentry_observation_date'),
        ('wiki', '0006_alter_wiki_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationentry',
            name='bird_photos',
            field=models.ManyToManyField(blank=True, related_name='observations', to='wiki.birdphoto', verbose_name='Фотографии птицы'),
        ),
        migrations.AddField(
            model_name='observationentry',
            name='location_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='Birds.location', verbose_name='Локация наблюдения'),
        ),
        migrations.AddField(
            model_name='observationentry',
            name='migration_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='Birds.migrationroute', verbose_name='Маршрут миграции'),
        ),
        migrations.AddField(
            model_name='observationentry',
            name='nesting_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='Birds.nestingsite', verbose_name='Гнездовье'),
        ),
        migrations.AddField(
            model_name='observationentry',
            name='nesting_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='Birds.nestingstatus', verbose_name='Статус гнездования'),
        ),
        migrations.AddField(
            model_name='observationentry',
            name='sighting_during_migration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='Birds.sightingduringmigration', verbose_name='Наблюдение во время миграции'),
        ),
    ]
