# Generated by Django 6.0.4 on 2026-05-21 09:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Birds', '0004_alter_birdspecies_name_alter_location_name_and_more'),
        ('user', '0006_observationentry_bird_photos_and_more'),
        ('wiki', '0006_alter_wiki_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observationentry',
            name='wiki_article',
        ),
        migrations.AddField(
            model_name='observationentry',
            name='wiki_articles',
            field=models.ManyToManyField(blank=True, related_name='observations', to='wiki.wiki', verbose_name='Связанные статьи'),
        ),
        migrations.RemoveField(
            model_name='observationentry',
            name='bird_species',
        ),
        migrations.AlterField(
            model_name='observationentry',
            name='observation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата наблюдения'),
        ),
        migrations.AddField(
            model_name='observationentry',
            name='bird_species',
            field=models.ManyToManyField(blank=True, related_name='observations', to='Birds.birdspecies', verbose_name='Виды птиц'),
        ),
    ]
