import { Observation } from '../types/observation';

export const INITIAL_OBSERVATIONS: Observation[] = [
  {
    id: 1001,
    birdName: "Балобан (Falco cherrug)",
    family: "Соколиные",
    status: "исчезающий",
    statusText: "Исчезающий вид",
    statusClass: "endangered",
    location: "Акбулакский район",
    notes: "Охота на жаворонков, активный полёт.",
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    timestamp: Date.now() - 2 * 24 * 60 * 60 * 1000,
    favorite: true,
    photo: null,
  },
  {
    id: 1002,
    birdName: "Степной орёл (Aquila nipalensis Hodgson)",
    family: "Ястребиные",
    status: "исчезающий",
    statusText: "Исчезающий вид",
    statusClass: "endangered",
    location: "Светлинский заказник",
    notes: "Парил над степью, высматривал добычу",
    date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    timestamp: Date.now() - 1 * 24 * 60 * 60 * 1000,
    favorite: false,
    photo: null,
  },
  {
    id: 1003,
    birdName: "Розовый скворец (Sturnus roseus)",
    family: "Скворцовые",
    status: "редкий",
    statusText: "Редкий вид",
    statusClass: "rare",
    location: "Оренбург",
    notes: "Стая около 50 птиц, кормились на земле",
    date: new Date().toISOString().split('T')[0],
    timestamp: Date.now(),
    favorite: true,
    photo: null,
  },
  // Дополнительные статьи-наблюдения
  {
    id: 1004,
    birdName: "📖 Статья: Как помочь птицам зимой",
    family: "Познавательное",
    status: "обычный",
    statusText: "Полезная информация",
    statusClass: "common",
    location: "Оренбургская область",
    notes: "Устраивайте кормушки с несолёным салом, семечками, крупой. Не забывайте добавлять воду.",
    date: new Date().toISOString().split('T')[0],
    timestamp: Date.now() - 3 * 24 * 60 * 60 * 1000,
    favorite: false,
    photo: null,
  },
  {
    id: 1005,
    birdName: "📖 Статья: Красная книга Оренбуржья",
    family: "Познавательное",
    status: "обычный",
    statusText: "Полезная информация",
    statusClass: "common",
    location: "Регион",
    notes: "В Оренбургской области охраняется более 90 видов птиц, включая дрофу, балобана, сапсана, степного орла.",
    date: new Date().toISOString().split('T')[0],
    timestamp: Date.now() - 4 * 24 * 60 * 60 * 1000,
    favorite: false,
    photo: null,
  },
  {
    id: 1006,
    birdName: "📖 Статья: Степной орёл – символ степи",
    family: "Познавательное",
    status: "обычный",
    statusText: "Полезная информация",
    statusClass: "common",
    location: "Степная зона",
    notes: "Крупная хищная птица, гнездится на деревьях и скалах. Находится под угрозой исчезновения.",
    date: new Date().toISOString().split('T')[0],
    timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000,
    favorite: false,
    photo: null,
  },
];