# Generated by Django 6.0.4 on 2026-04-23 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birdcall',
            name='author',
        ),
        migrations.RemoveField(
            model_name='birdcall',
            name='name',
        ),
    ]
