# Generated by Django 6.0.4 on 2026-05-13 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Birds', '0002_rename_nesting_site_sightingduringmigration_during_migration_and_more'),
        ('wiki', '0002_remove_birdcall_author_remove_birdcall_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdcall',
            name='bird_species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Birds.birdspecies', verbose_name='Вид птицы'),
        ),
        migrations.AddField(
            model_name='birdcall',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Название звука/крика'),
        ),
        migrations.AlterField(
            model_name='birdcall',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание звука'),
        ),
    ]
