# Generated by Django 6.0.4 on 2026-05-13 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Birds', '0002_rename_nesting_site_sightingduringmigration_during_migration_and_more'),
        ('wiki', '0003_birdcall_bird_species_birdcall_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birdphoto',
            name='author',
        ),
        migrations.RemoveField(
            model_name='birdphoto',
            name='bird_photo',
        ),
        migrations.AddField(
            model_name='birdphoto',
            name='bird_species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Birds.birdspecies', verbose_name='Вид птицы'),
        ),
        migrations.AddField(
            model_name='birdphoto',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание фото'),
        ),
        migrations.AddField(
            model_name='birdphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bird_photos/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='birdphoto',
            name='photographer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фотограф'),
        ),
        migrations.AddField(
            model_name='birdphoto',
            name='wiki',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.wiki', verbose_name='Связанная статья'),
        ),
        migrations.AlterField(
            model_name='birdphoto',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название фото'),
        ),
    ]
