# Generated by Django 6.0.4 on 2026-05-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_remove_birdphoto_author_remove_birdphoto_bird_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiki',
            name='author',
            field=models.TextField(blank=True, null=True, verbose_name='Автор статьи'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание статьи'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
