# Generated by Django 6.0.4 on 2026-05-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_alter_wiki_author_alter_wiki_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiki',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название статьи'),
        ),
    ]
