# Generated by Django 6.0.4 on 2026-04-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Birds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sightingduringmigration',
            old_name='nesting_site',
            new_name='during_migration',
        ),
        migrations.AddField(
            model_name='birdspecies',
            name='conservation_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='birdspecies',
            name='family',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='birdspecies',
            name='typical_nesting',
            field=models.TextField(blank=True, null=True),
        ),
    ]
