# Generated by Django 6.0.4 on 2026-05-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Birds', '0002_rename_nesting_site_sightingduringmigration_during_migration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birds',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='birds',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='birdspecies',
            name='conservation_status',
            field=models.TextField(blank=True, null=True, verbose_name='Статус сохранения'),
        ),
        migrations.AlterField(
            model_name='birdspecies',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='birdspecies',
            name='family',
            field=models.TextField(blank=True, null=True, verbose_name='Семейство'),
        ),
        migrations.AlterField(
            model_name='birdspecies',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='birdspecies',
            name='typical_nesting',
            field=models.TextField(blank=True, null=True, verbose_name='Типичное гнездование'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='migrationroute',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='migrationroute',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='nestingsite',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='nestingsite',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='nestingstatus',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='nestingstatus',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='sightingduringmigration',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sightingduringmigration',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
