# Generated by Django 6.0.4 on 2026-05-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Birds', '0003_alter_birds_description_alter_birds_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdspecies',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='migrationroute',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='nestingsite',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='nestingstatus',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='sightingduringmigration',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
